run:
  timeout: 5m
  tests: true

output:
  formats: colored-line-number

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
    - misspell
    - revive

linters-settings:
  gosec:
    excludes:
      - G104
  revive:
    rules:
      - name: exported

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
