server {
    listen 3000;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /health/live {
        access_log off;
        return 200 '{"service":"frontend","status":"alive","version":"0.1.0","request_id":"nginx"}';
        add_header Content-Type application/json;
    }
}
