"""Local dependency environment lifecycle support (SF02).

Typed entities, manifest loading/validation, and lifecycle state transitions
live in :mod:`workflow.local_env.models` (T014); canonical workspace identity,
secure runtime directories, and the per-project POSIX advisory lock live in
:mod:`workflow.local_env.identity` (T017).
"""

from __future__ import annotations

from .identity import (
    COMPOSE_PROJECT_DIR_NAME,
    LOCK_FILE_NAME,
    PROJECT_PREFIX,
    WORKSPACE_FINGERPRINT_LENGTH,
    WORKSPACE_HASH_LENGTH,
    ProjectLock,
    WorkspaceIdentity,
    acquire_project_lock,
    canonical_workspace_path,
    ensure_project_runtime_dir,
    secure_runtime_base,
    verify_fingerprint_ownership,
    workspace_identity,
)
from .models import (
    SAFE_REASON_MAX_LENGTH,
    ComposeSecretMaterial,
    DependencyHealthResult,
    DependencyId,
    DependencyInstance,
    Durability,
    EphemeralStorageDefinition,
    InstanceHealth,
    InstanceState,
    InvalidStateTransitionError,
    LifecycleAction,
    LifecycleOperation,
    LifecyclePhase,
    LivenessState,
    LocalDependencyDefinition,
    LocalDependencyManifest,
    LocalEnvironmentError,
    LockSafetyError,
    ManifestProject,
    ManifestRuntime,
    ManifestTimeouts,
    ManifestValidationError,
    NamedVolumeDefinition,
    OperationInProgressError,
    OperationStatus,
    OwnershipConflictError,
    PlatformDigests,
    ProbeKind,
    ReadinessService,
    ReadinessState,
    SecretCleanupState,
    SecretPurpose,
    SecretTransport,
    ServiceDependencyResult,
    ServiceReadinessResult,
    ServiceReadinessStatus,
    load_manifest,
    parse_manifest,
)

__all__ = [
    "COMPOSE_PROJECT_DIR_NAME",
    "LOCK_FILE_NAME",
    "PROJECT_PREFIX",
    "SAFE_REASON_MAX_LENGTH",
    "WORKSPACE_FINGERPRINT_LENGTH",
    "WORKSPACE_HASH_LENGTH",
    "ComposeSecretMaterial",
    "DependencyHealthResult",
    "DependencyId",
    "DependencyInstance",
    "Durability",
    "EphemeralStorageDefinition",
    "InstanceHealth",
    "InstanceState",
    "InvalidStateTransitionError",
    "LifecycleAction",
    "LifecycleOperation",
    "LifecyclePhase",
    "LivenessState",
    "LocalDependencyDefinition",
    "LocalDependencyManifest",
    "LocalEnvironmentError",
    "LockSafetyError",
    "ManifestProject",
    "ManifestRuntime",
    "ManifestTimeouts",
    "ManifestValidationError",
    "NamedVolumeDefinition",
    "OperationInProgressError",
    "OperationStatus",
    "OwnershipConflictError",
    "PlatformDigests",
    "ProbeKind",
    "ProjectLock",
    "ReadinessService",
    "ReadinessState",
    "SecretCleanupState",
    "SecretPurpose",
    "SecretTransport",
    "ServiceDependencyResult",
    "ServiceReadinessResult",
    "ServiceReadinessStatus",
    "WorkspaceIdentity",
    "acquire_project_lock",
    "canonical_workspace_path",
    "ensure_project_runtime_dir",
    "load_manifest",
    "parse_manifest",
    "secure_runtime_base",
    "verify_fingerprint_ownership",
    "workspace_identity",
]
